name: SampleStaticLibraryD
sln_path: Project/windows/SampleStaticLibraryD.sln
dependencies:
  - masahikotsujita/SampleStaticLibraryB
  - masahikotsujita/SampleStaticLibraryC
artifacts:
  include_headers:
    - Include/*
  link_libraries:
    - Dist/SampleStaticLibraryD_${PLATFORM}_${CONFIGURATION}.lib
