name: SampleStaticLibraryD
sln_path: Project/windows/SampleStaticLibraryD.sln
dependencies:
  - masahikotsujita/SampleStaticLibraryB
  - masahikotsujita/SampleStaticLibraryC
artifacts:
  - src: Include/*
    dst: ${ARTIFACTS_ROOT}/include/
  - src: Dist/*
    dst: ${ARTIFACTS_ROOT}/lib/

