name: SampleStaticLibraryD
sln_path: Project/windows/SampleStaticLibraryD.sln
dependencies:
  - project: masahikotsujita/SampleStaticLibraryB
    version: ^1.0.0
  - project: masahikotsujita/SampleStaticLibraryC
    version: ^1.0.0
artifacts:
  include_headers:
    - Include/*
  link_libraries:
    - Dist/SampleStaticLibraryD_${PLATFORM}_${CONFIGURATION}.lib
